---
title: "My Analysis"
author: "Your Name"
format: html
---

# Clean and wrangle data

## Setup

```{r}
library(dplyr)
library(tidyr)
library(readr)
```

## Source data

### Read data

```{r}
catch_original <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

```{r}
#| label: show_data
colnames(catch_original)
head(catch_original)
summary(catch_original)
glimpse(catch_original)
```

## Clean and reshape data

```{r}
catch_data <- catch_original %>% 
    select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
```

```{r}
# Use a conditional to fix the bad value, then make the column numeric
catch_clean <- catch_data %>%
    dplyr::mutate(
        Chinook = dplyr::if_else(condition = Chinook == "I", 
            true = "1",
            false = Chinook),
        Chinook = as.numeric(Chinook))

```

```{r}
# Pivot all columns except Region and Year into long format
catch_long <- catch_clean %>% 
    tidyr::pivot_longer(cols = -c(Region, Year),
        names_to = "species",
        values_to = "catch_thousands")

# Check the result
head(catch_long)
```

```{r}
# Pivot the data back into wide format
catch_wide <- catch_long %>%
    tidyr::pivot_wider(names_from = species,
        values_from = catch_thousands,
        values_fill = 0)

# Check the result
head(catch_wide)
```


```{r}
catch_long <- catch_long %>% 
    mutate(catch = catch_thousands * 1000) %>% 
    select(-catch_thousands)
head(catch_long)
```

```{r}
mean_region <- catch_long %>% 
    group_by(Region) %>% 
    summarize(mean_catch = mean(catch, na.rm = TRUE), .groups = "drop") %>% 
    arrange(desc(mean_catch))

head(mean_region)
```


```{r}
sse_catch <- catch_long %>% 
    filter(Region == "SSE")

head(sse_catch)
```


```{r}
sites_df <- data.frame(site = c("HAW-101", "HAW-103", "OAH-320", "OAH-219", "MAU-039"))

# Split site by the dash between the site letters and its code
sites_df %>%
    tidyr::separate_wider_delim(
        cols = site, 
        delim = "-",
        names = c("island", "site_number"), cols_remove = FALSE)

```


```{r}
dates_df <- data.frame(
    year  = rep(x = "1930", times = 3),
    month = rep(x = "12",   times = 3),
    day   = 14:16)

# Check that
dates_df

# Combine those columns into a single 'date' column
dates_df %>%
    tidyr::unite(col = date, 
        year, month, day,
        sep = "-", 
        remove = FALSE)
```
